export const dbMapping = {
  Grama: ["grass"],
  Neutro: ["neutral"],
  Água: ["water"],
  "Elétrico/Dragão": ["electric", "dragon"],
  "Dragão/Elétrico": ["dragon", "electric"],
  "Gelo/Sombrio": ["ice", "dark"],
  Terra: ["ground"],
  Gelo: ["ice"],
  "Dragão/Água": ["dragon", "water"],
  "Dragão/Fogo": ["dragon", "fire"],
  Fogo: ["fire"],
  "Gelo/Dragão": ["ice", "dragon"],
  Elétrico: ["electric"],
  "Grama/Dragão": ["grass", "dragon"],
  "Grama/Terra": ["grass", "ground"],
  "Terra/Grama": ["ground", "grass"],
  Dragão: ["dragon"],
  "Fogo/Sombrio": ["fire", "dark"],
  Sombrio: ["dark"],
  "Grama/Água": ["grass", "water"],
  "Água/Dragão": ["water", "dragon"],
  "Água/Gelo": ["water", "ice"],
  "Dragão/Sombrio": ["dragon", "dark"],
  "Sombrio/Terra": ["dark", "ground"],
  "Fogo/Terra": ["fire", "ground"],
  "Gelo/Terra": ["ice", "ground"],
};
